services:
  api:
    build:  # ¡Mantén esto para construir la imagen!
      context: .
      dockerfile: Dockerfile
    
    env_file: .env #carga las variables automaticamente
    ports:
      - "5000:80"  # Mapeo local
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - aspnetkeys:/var/aspnetkeys  # Para DataProtection
volumes:
  aspnetkeys:
      

  # frontend:  
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - api